version: "3.7"
services:
  rocket:
    container_name: rocket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  mongo:
    container_name: mongo
    image: andresvidal/rpi3-mongodb3:latest
    volumes: 
      - /data/db:/data/db
      - /data/configdb:/data/configdb
    ports:
      - "27017:27017"
      - "28017:28017"
    command: mongod
    