version: "3.7"
services:
  rocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  mongo:
    image: mongo:latest
    volumes: 
      - /mongodb_data:/data/db
    ports:
      - "27017:27017"